### ISSUE TITLE
Not working _prepare_file_upload.

### ISSUE THREAD

**Issue by andersdu** [iamleot/transferwee#38]
hi @iamleot 

Great work! I've been using it for quite a while and it was working great, but recently I keep receiving below errors:
```
Checking that all files exists
Checking for no duplicate filenames
Preparing to upload
Get transfer id b8b1cb5fb7a594c69dca110589851adf20230403142526
Uploading test.txt as part of transfer_id b8b1cb5fb7a594c69dca110589851adf20230403142526
{'message': 'Transfer already closed (state: processing)'}
Traceback (most recent call last):
  File "/Volumes/workspace/Robox/ROS/ws/cloud_tools/transferwee.py", line 443, in <module>
    print(upload(args.files, args.n, args.m, args.f, args.t))
  File "/Volumes/workspace/Robox/ROS/ws/cloud_tools/transferwee.py", line 380, in upload
    file_id = _prepare_file_upload(transfer_id, f, s)['id']
KeyError: 'id'
```

Are you aware of this issue? is it because the wetransfer server changed recently?

Thanks.

**Comment by iamleot** [comment]
Yes, it seems that part regarding chunk uploads changed (it seems there is some "storm"-named stuffs).

I think it needs to be readjusted. I will hopefully try to find some time to investigate and hopefully implement that in the next days!

Thanks for the notice!

**Comment by felps-dev** [comment]
Theres a code that might help:
```python
import base64
import hashlib
import json
import os
import re
from time import sleep
from typing import List

import requests

WETRANSFER_API_URL = "https://wetransfer.com/api/v4/transfers"
WETRANSFER_UPLOAD_LINK_URL = WETRANSFER_API_URL + "/link"
WETRANSFER_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0"
)


def _prepare_session():
    """Prepare a wetransfer.com session.

    Return a requests session that will always pass the required headers
    and with cookies properly populated that can be used for wetransfer
    requests.
    """
    s = requests.Session()
    s.headers.update({"User-Agent": WETRANSFER_USER_AGENT})
    r = s.get("https://wetransfer.com/")
    m = re.search('name="csrf-token" content="([^"]+)"', r.text)
    if not m:
        return None
    s.headers.update(
        {
            "x-csrf-token": m.group(1),
            "x-requested-with": "XMLHttpRequest",
        }
    )

    return s


def _file_name_and_size(file: str) -> dict:
    """Given a file, prepare the "name" and "size" dictionary.

    Return a dictionary with "name" and "size" keys.
    """
    filename = os.path.basename(file)
    filesize = os.path.getsize(file)

    return {"name": filename, "size": filesize}


def _prepare_link_upload(
    filenames: List[str], display_name: str, message: str, session
) -> dict:
    """Given a list of filenames and a message prepare for the link upload.

    Return the parsed JSON response.
    """
    j = {
        "files": [_file_name_and_size(f) for f in filenames],
        "display_name": display_name,
        "message": message,
        "ui_language": "en",
    }

    r = session.post(WETRANSFER_UPLOAD_LINK_URL, json=j)
    return r.json()


file_paths = ["nuvor icon.png"]

session = _prepare_session()

transfer_data = _prepare_link_upload(file_paths, "Test upload", "Hello World", session)
storm_token = transfer_data["storm_upload_token"]
transfer_id = transfer_data["id"]

# Step 1: Prepare data for preflight request
items = []

for file_path in file_paths:
    file_size = os.path.getsize(file_path)
    items.append(
        {
            "path": file_path,
            "item_type": "file",
            "blocks": [{"content_length": file_size}],
        }
    )

data = {"items": items}
headers = {"Content-Type": "application/json", "Authorization": f"Bearer {storm_token}"}


# Step 2: Send preflight request
preflight_url = "https://storm-us-east-1.wetransfer.net/api/v2/batch/preflight"
response = session.post(preflight_url, headers=headers, data=json.dumps(data))
response_data = response.json()
print(response_data)
if not response_data["ok"]:
    print("Error in preflight request")
    exit()

# Step 3: Prepare data for blocks request
blocks = []
for item in items:
    file_path = item["path"]
    content_length = item["blocks"][0]["content_length"]

    with open(file_path, "rb") as f:
        content = f.read()
        content_md5_hex = hashlib.md5(content).hexdigest()

    blocks.append(
        {"content_length": content_length, "content_md5_hex": content_md5_hex}
    )

data = {"blocks": blocks}

# Step 4: Send blocks request
blocks_url = "https://storm-us-east-1.wetransfer.net/api/v2/blocks"
response = session.post(blocks_url, headers=headers, data=json.dumps(data))
response_data = response.json()
print(response_data)

if not response_data["ok"]:
    print("Error in blocks request")
    exit()

# Step 5: Upload each block using PUT
put_headers = {}
for idx, block_data in enumerate(response_data["data"]["blocks"]):
    file_path = file_paths[idx]
    put_url = block_data["presigned_put_url"]

    with open(file_path, "rb") as f:
        content = f.read()

    for header, value in block_data["put_request_headers"].items():
        put_headers[header] = value

    response = session.put(put_url, headers=put_headers, data=content)
    print(response.text)

    if response.status_code != 200:
        print(f"Error in uploading file {file_path}")
        exit()

# Step 6: POST to https://storm-us-east-1.wetransfer.net/api/v2/batch
items = []
for idx, file_path in enumerate(file_paths):
    items.append(
        {
            "path": file_path,
            "item_type": "file",
            "block_ids": [response_data["data"]["blocks"][idx]["block_id"]],
        }
    )

data = {"items": items}
batch_ok = False
while not batch_ok:
    response = session.post(
        "https://storm-us-east-1.wetransfer.net/api/v2/batch",
        headers=headers,
        data=json.dumps(data),
    )
    response_data = response.json()
    print(response_data)

    if not response_data["ok"]:
        batch_ok = False
    else:
        batch_ok = True
    sleep(1)

# Step 7: Finalize the flow
finalize_url = f"https://wetransfer.com/api/v4/transfers/{transfer_id}/finalize"
response = session.put(
    finalize_url,
    {
        "wants_storm": True,
    },
    headers={
        "User-Agent": WETRANSFER_USER_AGENT,
        "content-type": "application/json",
    },
)

response_data = response.json()
breakpoint()

if "shortened_url" in response_data:
    print("Download URL:", response_data["shortened_url"])
else:
    print("Error in finalizing transfer")

```

**Comment by felps-dev** [comment]
For some reason, im getting:
```json
{'type': '__generic__', 'encoded_error': 'v0:bOpymfj36Fz9leQ2is4WN2VaOhAXorTKNfm0juCgLowZ+Gv91nLn/tQnf2BCSjd+4L1pOtazrQL0UqgxDTTeI3TMLscBWN2zLqX93Hi6uvpNaNNY/2oPqTH1Wxv/bdGmg+2yv0eMhfSf1r+tYk1o4OYorUs/tSM2zfB/QUIkYcGeE3BZyxawHvtyO6OOhFqx9udCbtYA0j6QfGsZDTFxfzcp/7hnWxIx30w3c8swZru2Tv4pDM13K5yWIseRUzSUgBlw1SDoncqUzyNiEDMLcpnXrWwJF8vQrP/qJ8nH/Ui3a/9+OFh5CgCbPZft5QTxiYQIoqvuqEZhMTcUEWoY9Q1RQGBHzHpdAYQ1m79SpndJmUm8uEFxjvYE2C4exTZwbspAbFMBpfI7SW0dbQjTaHbjZ7KIBaaWItP1XvjY3H0V24eig9WC4FPXoQFSnRr53cTX5ckfUMCR+e4+bhteNqdSBTTGT7AK0juPplY2+tT6XxSnW+gkePQho6QtaaqCJjyTAKL9HUw/B2QUjkz+AZxAoWtppjCDnYmhk0Tk5UBYcXmIZbWPcZWtqTBDIfm+yHD241CB41XcNLnBrzjeEKbGrbAV3b5Htme1ujsvk1YnO6pdd2lIFeUS0fg3TN5Hh91pf/crRBAybPPSWBRJkNpVbv9PhrKoAmcbZ852+ET4+6nho2tufsLYnKCKNQH9R+K5wSkv/zdwdiDmyLKhvSlna5h82cHyXJMlBhCGqxlO6Al9Hpp6Jj6fMhlDB9y1aPuK2tnP+pv3CQkmeu4qCT2IrqBRYI4XGxh++NVRez7rgkOvB8DnJqDfX6JEVEb8g+gNLI8ccj6OTVeZ34WAgTiV1w+aRBmH+dwcJhwP+Ks7DCZfNvVaJnsdzjPSGfqJbpUWPEgxGLq3NBLmWygBy9uh8itfXIUEIgU6c45DgiCCZKSqKBNfBu4dbsp7FMPjG5uHjbnws6Fwmms9t1n/fhzeYzDoI+BVuDvgamGHXqnEu1GNKaFq4P/f8WKkuvRd4XToUHSS23suWGVcbEToBdoIEZVJX1LNsWP9ippfm6goxQoAcbsmUVnqtBeRBjTRqqz9ojMH18I6Ha5BklwbWccMTFImL80t7EvN+XUz94XAp7iTcmP6shGzEnOP32xve48P5AWk9hXfRNrJqovbY1sFfYMjz3EI5qdh/s8ItO7aT7/Fh7YJQwUwPSn7w3qXzfPbPxHpbjn344kWCTyw9uXpldGL1+2E8DLpG6YhzyHb14byrVlOS4MHK9ZRvPhSWNKXn6aI9T0gJ9cl2AcD7+pYQWzXETntxq5giiLxU9q9srrexoIxfIp0kryOUFz0V7EEfcNzW/QxIMJFTqMsqOGv17GHbYEoPNHFP38rkutlyYd8kBdriYM70Z/cII+HvkPxogLR7uIZeIy+tENYFS3WVFQ0Sls36Z99PMooID0//IHhVibm11zyBm3aTByn1OyQvTsirMPVK64VQ4I2cwke6iRh7PPMeR/2Co2oYHxAMTjQlSUPWd6Fc9vPPJn36nQFnRwUSNS5fDYlmRMBaLN30xtBY3BF8lCt35/4sv4U62pwwzf8hSYdYR7xDOd3jhNP1uFYvQ/c1zzkXxIHKr19mFldIc5OaeH35AgwauFq9PHB7AcVguF+QHyuSSSRTlzeqARzWwbiEIndjh8IFBCmecJfkGy6qHoCkOEu6zSBpu65UlpDsyE/t4/K+oge32JcHs/VODHV368y+jVGpwsVu65Q+n9vW0eLk7hd3QScJpb+8KGeOuWrYH5b2vh5s5mttVdga6FPsiGHws7YL7vR/wq8iXtSHI7NFqJHtADtxbcDIOY6bUeynmcaqpJVhaYw+F/nXDOp4kthh1TNQBPJaNs/+2s/oytme2XMkKjIfKsveCuweBM5/gJBqA5tnmoIbp1O6NtA8k9yEzyehxm0860r36rjDI+UO9+l089o54yty87l8qhKPkjALoPFjjLycMt2N6otulmo0X/ZGGxltFJuLKbziCA4QMxJ/eueP8STe8YcrwNLetyzlVkb6vPoBHSQuCuPDKcOw5ttHRFt+FMNvQeI0MoT/0JcZkIFmBLAuw/nJ7jZCVm7DtFYcbVv+B111Q7wWPUfRfOICktQPZdRB8u8sgFfJBaFDBZS60rNwIr4MIepo/3Fx+Cx33Zi+R7v1lEQpXcVuhEx/xYub3+VYgjE4IEnwbP3H/g=', 'encoded_error_suggestion': "You can try again or let us know what happened. Send your error code to support@wetransfer.com and we'll try to help!", 'message': '(suppressed)'}
```
Don't know why yet

**Comment by felps-dev** [comment]
If someone seeing this are on trouble because the recent changes of wetransfer, I made a code that uses file.io with the same behavior, it saved me.
```python
import os
from typing import List

import requests


def create_folder(download_name: str, download_title: str) -> str:
    url = "https://file.io/~"
    data = {
        "name": download_name,
        "title": download_title,
        "nodeType": "folder",
        "autoDelete": True,
        "expires": "2w",
        "maxDownloads": 1,
    }
    session = requests.Session()
    response = session.post(url, json=data)
    if response.status_code == 200:
        response_data = response.json()
        if response_data["success"]:
            access_token = response.headers["x-file-io-anonymous-access-token"]
            download_link = response_data["link"]
            return access_token, download_link, session
        else:
            raise Exception("Error creating folder: " + response.text)
    else:
        raise Exception("Error creating folder: " + response.text)


def upload_files(
    access_token: str, file_paths: List[str], session, download_name
) -> None:
    for file_path in file_paths:
        file_name = os.path.basename(file_path)
        url = f"https://file.io/~/{download_name}"
        headers = {
            "authorization": f"Bearer {access_token}",
        }
        with open(file_path, "rb") as file:
            files = {"file": file}
            response = session.post(url, headers=headers, files=files)
            if response.status_code != 200:
                raise Exception(f"Error uploading file {file_name}: " + response.text)


def upload(files, name):
    download_name = "Arquivo"
    download_title = name
    file_paths = files

    access_token, download_link, session = create_folder(download_name, download_title)
    upload_files(access_token, file_paths, session, download_name)

    print("All files uploaded successfully.")
    return download_link
```

**Comment by Alecsplus** [comment]
Any news on it?

**Comment by iamleot** [comment]
No, sorry, I had no time/energy to look at it!

**Comment by iamleot** [comment]
PR #39 should fix this issue.

If there are any problems/regressions please open separate issues!

Thank you for the patience!

**Comment by Alecsplus** [comment]
It Works! thanks for your support.
