### ISSUE TITLE
Can't upload files: http.client.RemoteDisconnected

### ISSUE THREAD

**Issue by marcelpaulo** [iamleot/transferwee#6]
I'm finally plugging transferwee into my bash script that sends albums from quodlibet, but I'm not being able to upload any files. I manage to upload the same files using the Web interface on a browser. Perhaps it's a problem with the WeTransfer API, I don't know.

Here's the test file I have been trying to upload:

```
paulo:~/tmp$ ls -l foo/bar
-rw-rw-r-- 1 paulo paulo 9 jun  2 18:58 foo/bar
```

and here's the output:

```
paulo:~/tmp$ transferwee upload -f marcelpaulo@gmail.com -t marcelpaulo@gmail.com -- foo/bar
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paulo/.local/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paulo/.local/bin/transferwee", line 325, in <module>
    print(upload(args.files, args.m, args.f, args.t))
  File "/home/paulo/.local/bin/transferwee", line 282, in upload
    _upload_chunks(transfer_id, file_id, f)
  File "/home/paulo/.local/bin/transferwee", line 217, in _upload_chunks
    'Access-Control-Request-Method': 'PUT',
  File "/home/paulo/.local/lib/python3.6/site-packages/requests/api.py", line 85, in options
    return request('options', url, **kwargs)
  File "/home/paulo/.local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/paulo/.local/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/paulo/.local/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/paulo/.local/lib/python3.6/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

I'm running latest master (5d921f6) on Xubuntu 18.04.02

**Comment by iamleot** [comment]
Hello Paulo, 

Paulo Marcel Coelho Aragão writes:
> I'm finally plugging transferwee into my bash script that sends albums from quodlibet, but I'm not being able to upload any files. I manage to upload the same files using the Web interface on a browser. Perhaps it's a problem with the WeTransfer API, I don't know.
>
> Here's the test file I have been trying to upload:
>
> ```
> paulo:~/tmp$ ls -l foo/bar
> -rw-rw-r-- 1 paulo paulo 9 jun  2 18:58 foo/bar
> ```
>
> and here's the output:
>
> ```
> paulo:~/tmp$ transferwee upload -f marcelpaulo@gmail.com -t marcelpaulo@gmail.com -- foo/bar
> ```
> [...]

I have just tried to reproduce it (but with a 16M file that also
exercise multiple chunks code paths and with different `-f' and
`-t' arguments) and unfortunately I wasn't able to reproduce it (both
upload and download were successfull).

Can you please retry it? (maybe it was a temporary network issue?)

**Comment by iamleot** [comment]
Leonardo Taccari writes:
> [...]
> 
> Can you please retry it? (maybe it was a temporary network issue?)
> 

...and, forgot to say, but if you are more curious I suggest to retry it
by using mitmproxy with the browser and with transferwee in order to see
(but also log/save and probably more!) all HTTP requests and responses.

Regarding transferwee (or, more in general any Python scripts that uses
requests package) setting the following environment variables after
starting `mitmproxy' should do the trick:

 $ export REQUESTS_CA_BUNDLE="${HOME}/.mitmproxy/mitmproxy-ca-cert.pem"
 $ export http_proxy=http://localhost:8080
 $ export https_proxy=http://localhost:8080
 [... then you can run transferwee or any requests scripts/module as usual...]

**Comment by marcelpaulo** [comment]
> Can you please retry it? (maybe it was a temporary network issue?)

Please forgive me, it was indeed a network glitch. I can't reproduce it either. I can upload now without any problems.

Apologies for raising an unnecessary issue!

**Comment by marcelpaulo** [comment]
> ...and, forgot to say, but if you are more curious I suggest to retry it by using mitmproxy with the browser and with transferwee in order to see (but also log/save and probably more!) all HTTP requests and responses.

Hey, great tip, I'll sure try it out! Thanks!
