### ISSUE TITLE
Could not upload files bigger than 60MB

### ISSUE THREAD

**Issue by youcmd** [iamleot/transferwee#64]
the file only 68MB

`python transferwee.py upload -v "audio.m4a"`

```
Checking that all files exists
Checking for no duplicate filenames
Preparing to upload
Could not find any csrf-token
From storm_upload_token WETRANSFER_STORM_PREFLIGHT URL is: https://storm-us-east-1.wetransfer.net/api/v2/batch/preflight
From storm_upload_token WETRANSFER_STORM_BLOCK URL is: https://storm-us-east-1.wetransfer.net/api/v2/blocks
From storm_upload_token WETRANSFER_STORM_BLOCK URL is: https://storm-us-east-1.wetransfer.net/api/v2/batch
Get transfer id 84d0a30e9763ab565da61da02ae126c920230819085919
Doing preflight storm
Preparing storm block upload
Traceback (most recent call last):
  File "/content/transferwee.py", line 684, in <module>
    print(upload(args.files, args.n, args.m, args.f, args.t))
  File "/content/transferwee.py", line 588, in upload
    for f, b in zip(files, blocks["data"]["blocks"]):
KeyError: 'data'
```

i try add this code in 587 `logger.debug(blocks)`
```
{'ok': False, 'error': {'message': 'Block at position 0 ({:content_length=>71567915, :content_md5_hex=>"3dbb5db155ffebc8d7ce20c804ada891"}) is too large (max is 62914560)'}}
```

**Comment by iamleot** [comment]
I have adjusted the issue title according the very likely root case of the problem. I will try to reproduce it and hopefully fix it. I guess that we need to upload each file in block of 60MB or similar.

Thanks for the report and debug information!

**Comment by SaadDevCs** [comment]
Any solution for this issue ?

**Comment by iamleot** [comment]
Hello!
It needs fixing in several places. Basically around the code there are some `XXX:` comments that assumed that one single block upload was ok (but there are also some other places not marked with such comments). This assumption was wrong. I need to sit down and review and adjust all API calls related to file and block uploads.

As a possible workaround, at least on Unix `split(1)` can be used as a workaround.

**Comment by iamleot** [comment]
Please also see #70, probably the limit was changed!

**Comment by sharevb** [comment]
Updated with #76
